# Use an official Node runtime as a parent image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY frontend/package.json .
RUN npm install

# Bundle app source
COPY frontend/ .

# Build the app
RUN npm run build

# Install serve to serve the app on a container
RUN npm install -g serve

# Run serve to host the app
CMD ["serve", "-s", "build", "-l", "3000"]